test: Fix flaky `events-processor` test (#603)
## Context

One of the `events-processor` is flaky due to random order:

```sh
--- FAIL: TestEnrichEvent (0.01s)
    --- FAIL: TestEnrichEvent/When_event_source_is_not_post_process_on_API_with_multiple_flat_filters (0.00s)
        enrichment_service_test.go:302: 
                Error Trace:    /app/processors/event_processors/enrichment_service_test.go:302
                Error:          Not equal: 
                                expected: "charge_id1"
                                actual  : "charge_id2"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -charge_id1
                                +charge_id2
                Test:           TestEnrichEvent/When_event_source_is_not_post_process_on_API_with_multiple_flat_filters
        enrichment_service_test.go:307: 
                Error Trace:    /app/processors/event_processors/enrichment_service_test.go:307
                Error:          Not equal: 
                                expected: "charge_id2"
                                actual  : "charge_id1"
                            
                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -charge_id2
                                +charge_id1
                Test:           TestEnrichEvent/When_event_source_is_not_post_process_on_API_with_multiple_flat_filters
FAIL
FAIL    github.com/getlago/lago/events-processor/processors/event_processors    0.020s
```

## Description

This fixes it by ordering the result before doing assertions.

It also updates the README to explain how to run tests.